### ISSUE TITLE
UnboundLocalError:  local variable 'gz' referenced before assignment

### ISSUE THREAD

**Issue by TheTechRobo** [ArchiveTeam/megawarc#5]
I'm getting this error:

```
thetechrobo@thetechrobovps:/m/b/I/D/downsandson ❯❯❯ megawarc --verbose convert ../MEGAWARC.tar
Copying 1652740309829c5a3e1fc0bf20-1_1652740337.315711 to tar
Copying 1652740309829c5a3e1fc0bf20-1_1652740337.315711/wget.tmp to tar
Copying 1652740309829c5a3e1fc0bf20-1_1652740337.315711/wget.log to tar
Copying 1652740309829c5a3e1fc0bf20-1_1652740337.315711/funeralhome-1934cdbeadc09ac1a98713bb2b1d8ca41f8f2ec1-20220516-223149.warc.os.cdx.gz to tar
Checking 1652740309829c5a3e1fc0bf20-1_1652740337.315711/funeralhome-1934cdbeadc09ac1a98713bb2b1d8ca41f8f2ec1-20220516-223149.warc.gz
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/megaward-called", line 740, in <module>
    main()
  File "/home/thetechrobo/.local/bin/megaward-called", line 693, in main
    mwb.process()
  File "/home/thetechrobo/.local/bin/megaward-called", line 327, in process
    self.process_entry(tarinfo, warc_out, tar_out, json_out)
  File "/home/thetechrobo/.local/bin/megaward-called", line 362, in process_entry
    copy_to_file=warc_out, verbose=self.verbose)
  File "/home/thetechrobo/.local/bin/megaward-called", line 275, in test_gz
    args=(gz.stdout, d_wget_at)
UnboundLocalError: local variable 'gz' referenced before assignment
```
Here's the file it was `Checking`:

https://transfer.archivete.am/SWZGI/failed_on.warc.gz

**Comment by Arkiver2** [comment]
Should be fixed with https://github.com/ArchiveTeam/megawarc/commit/687ece11a2d4249d1f7c684b31854ef70298f2de.
